#!/usr/bin/env python3
"""Regenerate the INDEX.md of every markdown directory under the given roots.

Usage:
  python scripts/reindex.py <dir> [<dir> ...]

Each INDEX.md is a generated file→description table, so Claude can pick the
one file it needs instead of reading a directory's worth of prose. The
description comes from a `description:` field in the file's YAML frontmatter;
files without one are listed with a `—` so the gap is visible rather than
silent. INDEX.md files are overwritten wholesale — never hand-edit one.
"""

import re
import sys
from pathlib import Path

SKIP_DIRS = {".git", ".venv", "node_modules", "__pycache__", ".claude-plugin"}
# Loaded automatically or read on arrival; routing to them would be noise.
SKIP_FILES = {"INDEX.md", "CLAUDE.md", "README.md"}
HEADER = "<!-- Generated by scripts/reindex.py. Do not edit by hand. -->"
FRONTMATTER = re.compile(r"\A---\r?\n(.*?)\r?\n---\r?\n", re.DOTALL)
DESCRIPTION = re.compile(r"^description:\s*(.+?)\s*$", re.MULTILINE)


def describe(path: Path) -> str:
    match = FRONTMATTER.match(path.read_text(encoding="utf-8"))
    if not match:
        return "—"
    found = DESCRIPTION.search(match.group(1))
    return found.group(1).strip().strip("\"'") if found else "—"


def index_dir(directory: Path) -> bool:
    """Write directory/INDEX.md. Returns True if it was created or changed."""
    files = sorted(p for p in directory.glob("*.md") if p.name not in SKIP_FILES)
    subdirs = sorted(
        p for p in directory.iterdir()
        if p.is_dir() and p.name not in SKIP_DIRS and any(p.rglob("*.md"))
    )
    if not files and not subdirs:
        return False

    rows = [f"| [{p.name}/]({p.name}/INDEX.md) | *(directory)* |" for p in subdirs]
    rows += [f"| [{p.name}]({p.name}) | {describe(p)} |" for p in files]
    body = "\n".join([
        HEADER,
        "",
        f"# {directory.resolve().name}/",  # resolve: Path(".").name is empty
        "",
        "| File | Description |",
        "| --- | --- |",
        *rows,
        "",
    ])

    target = directory / "INDEX.md"
    if target.exists() and target.read_text(encoding="utf-8") == body:
        return False
    target.write_text(body, encoding="utf-8")
    return True


def main() -> None:
    roots = [Path(a) for a in sys.argv[1:]]
    if not roots:
        print(__doc__, file=sys.stderr)
        sys.exit(2)

    changed = 0
    for root in roots:
        if not root.is_dir():
            print(f"error: not a directory: {root}", file=sys.stderr)
            sys.exit(1)
        directories = [root] + [
            d for d in root.rglob("*")
            if d.is_dir() and not (set(d.parts) & SKIP_DIRS)
        ]
        for directory in directories:
            if index_dir(directory):
                print(f"reindexed: {directory / 'INDEX.md'}")
                changed += 1
    print(f"{changed} index file(s) written")


if __name__ == "__main__":
    main()
