#!/usr/bin/env python3
"""Regenerate a content workspace's INDEX.md files after a markdown edit.

Run as a plugin hook, so it fires in whatever project the user happens to be
in. It must therefore be a no-op everywhere except an actual content
workspace: it only acts when the project root already holds a generated
INDEX.md, so it can never start writing index files into an unrelated repo.
"""

import os
import subprocess
import sys
from pathlib import Path

MARKER = "<!-- Generated by scripts/reindex.py"

project = Path(os.environ.get("CLAUDE_PROJECT_DIR", "")).resolve()
index = project / "INDEX.md"
if not index.is_file() or MARKER not in index.read_text(encoding="utf-8"):
    sys.exit(0)

reindex = Path(__file__).resolve().parent / "reindex.py"
subprocess.run([sys.executable, str(reindex), str(project)], check=False)
