#!/usr/bin/env python3
"""Mirror a map's Verse source out of its UEFN project into its notes repo.

Usage:
  python sync_verse.py <map-dir> [<map-dir> ...]

The `.uefnproject` and its assets are binary and can't be reviewed in a diff,
but the Verse source can — so a map's repository keeps a copy of it. The copy
is a **one-way mirror**: the UEFN project is the only source, and nothing here
ever writes back. That removes the question of which side is authoritative,
which is what made the hand-maintained copies drift (they had even been
renamed, so "identical" had to be checked by reading them).

Reads `project_root` out of the map's CLAUDE.md, copies every .verse file
under it into `<map-dir>/verse/` preserving the original names and relative
paths, and deletes mirrored files whose source is gone.
"""

import re
import shutil
import sys
from pathlib import Path

PROJECT_ROOT = re.compile(r"^\s*-\s*\*\*project_root\*\*:\s*`(.+?)`\s*$", re.MULTILINE)
IGNORED = {"Intermediate", "Saved", "DerivedDataCache", "Binaries", ".git"}
HEADER = "<!-- Generated by scripts/sync_verse.py. Do not edit by hand. -->"


def project_root_of(map_dir: Path) -> Path | None:
    claude = map_dir / "CLAUDE.md"
    if not claude.is_file():
        return None
    found = PROJECT_ROOT.search(claude.read_text(encoding="utf-8"))
    if not found:
        return None
    root = Path(found.group(1))
    return root if root.is_dir() else None


def sources(root: Path) -> list[Path]:
    return [
        p for p in root.rglob("*.verse")
        if not (IGNORED & set(p.relative_to(root).parts))
    ]


def sync(map_dir: Path) -> int:
    root = project_root_of(map_dir)
    if root is None:
        print(f"skipped (no linked project_root): {map_dir}")
        return 0

    mirror = map_dir / "verse"
    mirror.mkdir(parents=True, exist_ok=True)
    found = sources(root)
    wanted = set()
    changed = 0

    for src in found:
        dest = mirror / src.relative_to(root)
        wanted.add(dest)
        if dest.is_file() and dest.read_bytes() == src.read_bytes():
            continue
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        print(f"mirrored: {dest}")
        changed += 1

    for stale in mirror.rglob("*.verse"):
        if stale not in wanted:
            stale.unlink()
            print(f"removed (gone upstream): {stale}")
            changed += 1

    rows = "\n".join(
        f"| [{p.relative_to(mirror).as_posix()}]({p.relative_to(mirror).as_posix()}) "
        f"| {p.stat().st_size} bytes |"
        for p in sorted(wanted)
    )
    index = (
        f"{HEADER}\n\n# verse/\n\n"
        f"A read-only mirror of the Verse source in `{root}`.\n"
        "Edit the originals there; anything written here is overwritten.\n\n"
        "| File | Size |\n| --- | --- |\n" + rows + "\n"
    )
    target = mirror / "INDEX.md"
    if not target.is_file() or target.read_text(encoding="utf-8") != index:
        target.write_text(index, encoding="utf-8")
        changed += 1

    print(f"{map_dir.name}: {len(found)} file(s) mirrored from {root}")
    return changed


def main() -> None:
    dirs = [Path(a) for a in sys.argv[1:]]
    if not dirs:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    total = sum(sync(d) for d in dirs)
    print(f"{total} change(s)")


if __name__ == "__main__":
    main()
