#!/usr/bin/env python3
"""Keep a content workspace's generated files current after an edit.

Runs as a plugin hook, so it fires in whatever project the user happens to be
in. It must therefore be a no-op everywhere except an actual content
workspace: it only acts when the project root already holds a generated
INDEX.md, so it can never start writing files into an unrelated repository.

Two jobs, both of things a person would otherwise have to remember:
mirroring each map's Verse source out of its UEFN project, and regenerating
every INDEX.md.
"""

import os
import subprocess
import sys
from pathlib import Path

MARKER = "<!-- Generated by scripts/reindex.py"

project = Path(os.environ.get("CLAUDE_PROJECT_DIR", "")).resolve()
index = project / "INDEX.md"
if not index.is_file() or MARKER not in index.read_text(encoding="utf-8"):
    sys.exit(0)

here = Path(__file__).resolve().parent
maps = [d for d in project.iterdir() if d.is_dir() and (d / "CLAUDE.md").is_file()]
if maps:
    subprocess.run(
        [sys.executable, str(here / "sync_verse.py"), *map(str, maps)], check=False
    )
subprocess.run([sys.executable, str(here / "reindex.py"), str(project)], check=False)
